### ISSUE TITLE
Misleading instructions

### ISSUE THREAD

**Issue by NStephenson** [learn-co-curriculum/sinatra-nested-forms#16]
It seems like this lab can only be properly solved by iterating over the instance variable of our ship objects, but the instruction in the h2 tags of the show.erb file wants each ship under each of the precoded headers. This makes the lab impossible to solve if following those directions and there are no directions that say iteration must be used. 

I can't tell why the spec requires iteration to be used by looking at it, so that part may not be true, but I the code I created without iteration gave the proper results but wouldn't pass the tests. 

I've pushed my working solution that wouldn't pass the tests under a second branch called "wrong-solution" if anyone wants  to view it in my repo.

**Comment by vicfriedman** [comment]
hey @NStephenson 

Thanks so much for raising this issue. It actually wasn't about your code, but more about the design of the tests.

The reason it fails without iteration, is that all the instance of the `Ship` class created in `spec/sinatra_forms_spec.rb` are stored in `@@ships`, by the time your test that is failing is run, there are already several other instances of the Ship class. So using `@ships[1]` is returning the second ship, which isn't `Flying Dutchman`

I hope that makes sense. I have sense corrected the tests to be more clear, and clear all instances of the `Ship` class so that your `wrong-solution` branch passes
